package net.mamby.health.ui.theme

import androidx.compose.ui.graphics.Color

internal val Teal = Color(0xFF0E7C73)
internal val TealDark = Color(0xFF005049)
internal val TealLight = Color(0xFF79D9D0)
internal val White = Color(0xFFFFFFFF)
internal val Neutral50 = Color(0xFFF7F7F7)
internal val Neutral100 = Color(0xFFF1F1F1)
internal val NeutralOutline = Color(0xFFE2E2E2)
internal val NeutralText = Color(0xFF1B1B1B)
internal val NeutralSecondaryText = Color(0xFF666666)
internal val DarkBackground = Color(0xFF111111)
internal val DarkSurface = Color(0xFF1B1B1B)
internal val DarkElevatedSurface = Color(0xFF242424)
internal val DarkOutline = Color(0xFF444444)
internal val DarkText = Color(0xFFF5F5F5)
internal val DarkSecondaryText = Color(0xFFBDBDBD)
internal val Info = Color(0xFF3267A8)
internal val InfoDark = Color(0xFF00325A)
internal val InfoLight = Color(0xFFA8C7FA)
internal val Danger = Color(0xFFB64646)
internal val DangerDark = Color(0xFF690005)
internal val DangerLight = Color(0xFFFFB4AB)

internal val ProfileBlueLight = Color(0xFFD2E4FF)
internal val OnProfileBlueLight = Color(0xFF004A78)
internal val ProfilePurpleLight = Color(0xFFE9DDFF)
internal val OnProfilePurpleLight = Color(0xFF4D3A69)
internal val ProfileOrangeLight = Color(0xFFFFDCC2)
internal val OnProfileOrangeLight = Color(0xFF663B14)
internal val ProfileRoseLight = Color(0xFFFFD9E2)
internal val OnProfileRoseLight = Color(0xFF6A2B43)
internal val ProfileGreenLight = Color(0xFFCDEDD7)
internal val OnProfileGreenLight = Color(0xFF1E5132)
internal val ProfileOliveLight = Color(0xFFE0E2C3)
internal val OnProfileOliveLight = Color(0xFF424916)

internal val ProfileBlueDark = Color(0xFF174A69)
internal val OnProfileBlueDark = Color(0xFFD2E4FF)
internal val ProfilePurpleDark = Color(0xFF49385E)
internal val OnProfilePurpleDark = Color(0xFFE9DDFF)
internal val ProfileOrangeDark = Color(0xFF5B3F27)
internal val OnProfileOrangeDark = Color(0xFFFFDCC2)
internal val ProfileRoseDark = Color(0xFF5F3445)
internal val OnProfileRoseDark = Color(0xFFFFD9E2)
internal val ProfileGreenDark = Color(0xFF264E37)
internal val OnProfileGreenDark = Color(0xFFCDEDD7)
internal val ProfileOliveDark = Color(0xFF444928)
internal val OnProfileOliveDark = Color(0xFFE0E2C3)
