package net.mamby.health.ui.theme

import androidx.compose.ui.graphics.Color

internal val Teal = Color(0xFF0E7C73)
internal val TealDark = Color(0xFF005049)
internal val TealLight = Color(0xFF79D9D0)
internal val TealContainer = Color(0xFFC8F0EB)
internal val OnTealContainer = Color(0xFF004F49)
internal val TealContainerDark = Color(0xFF174B47)
internal val OnTealContainerDark = Color(0xFF9CEDE4)
internal val White = Color(0xFFFFFFFF)
internal val Neutral50 = Color(0xFFF7F7F7)
internal val Neutral100 = Color(0xFFF1F1F1)
internal val NeutralOutline = Color(0xFFE2E2E2)
internal val NeutralText = Color(0xFF1B1B1B)
internal val NeutralSecondaryText = Color(0xFF666666)
internal val DarkBackground = Color(0xFF111111)
internal val DarkSurface = Color(0xFF1B1B1B)
internal val DarkElevatedSurface = Color(0xFF242424)
internal val DarkOutline = Color(0xFF444444)
internal val DarkText = Color(0xFFF5F5F5)
internal val DarkSecondaryText = Color(0xFFBDBDBD)
internal val Info = Color(0xFF3267A8)
internal val InfoDark = Color(0xFF00325A)
internal val InfoLight = Color(0xFFA8C7FA)
internal val Danger = Color(0xFFB64646)
internal val DangerDark = Color(0xFF690005)
internal val DangerLight = Color(0xFFFFB4AB)

internal val HomeTileYellowLight = Color(0xFFFFF0AE)
internal val OnHomeTileYellowLight = Color(0xFF3D2F00)
internal val HomeTileMintLight = Color(0xFFCDEED8)
internal val OnHomeTileMintLight = Color(0xFF153B23)
internal val HomeTileSkyLight = Color(0xFFD4E7FF)
internal val OnHomeTileSkyLight = Color(0xFF183A5A)
internal val HomeTileLavenderLight = Color(0xFFE7DEFF)
internal val OnHomeTileLavenderLight = Color(0xFF39295C)
internal val HomeTileCoralLight = Color(0xFFFFDAD2)
internal val OnHomeTileCoralLight = Color(0xFF5A1D13)
internal val HomeTilePeachLight = Color(0xFFFFE0C2)
internal val OnHomeTilePeachLight = Color(0xFF57300A)
internal val HomeTileAquaLight = Color(0xFFCBEDEA)
internal val OnHomeTileAquaLight = Color(0xFF123F3B)

internal val HomeTileYellowDark = Color(0xFF54470D)
internal val OnHomeTileYellowDark = Color(0xFFFFF0AE)
internal val HomeTileMintDark = Color(0xFF214C31)
internal val OnHomeTileMintDark = Color(0xFFD0F8DA)
internal val HomeTileSkyDark = Color(0xFF244764)
internal val OnHomeTileSkyDark = Color(0xFFD2E8FF)
internal val HomeTileLavenderDark = Color(0xFF443563)
internal val OnHomeTileLavenderDark = Color(0xFFE9DDFF)
internal val HomeTileCoralDark = Color(0xFF63382F)
internal val OnHomeTileCoralDark = Color(0xFFFFDAD2)
internal val HomeTilePeachDark = Color(0xFF5D4023)
internal val OnHomeTilePeachDark = Color(0xFFFFE1C2)
internal val HomeTileAquaDark = Color(0xFF204B47)
internal val OnHomeTileAquaDark = Color(0xFFCDF4EF)

internal val ProfileBlueLight = Color(0xFFD2E4FF)
internal val OnProfileBlueLight = Color(0xFF004A78)
internal val ProfilePurpleLight = Color(0xFFE9DDFF)
internal val OnProfilePurpleLight = Color(0xFF4D3A69)
internal val ProfileOrangeLight = Color(0xFFFFDCC2)
internal val OnProfileOrangeLight = Color(0xFF663B14)
internal val ProfileRoseLight = Color(0xFFFFD9E2)
internal val OnProfileRoseLight = Color(0xFF6A2B43)
internal val ProfileGreenLight = Color(0xFFCDEDD7)
internal val OnProfileGreenLight = Color(0xFF1E5132)
internal val ProfileOliveLight = Color(0xFFE0E2C3)
internal val OnProfileOliveLight = Color(0xFF424916)

internal val ProfileBlueDark = Color(0xFF174A69)
internal val OnProfileBlueDark = Color(0xFFD2E4FF)
internal val ProfilePurpleDark = Color(0xFF49385E)
internal val OnProfilePurpleDark = Color(0xFFE9DDFF)
internal val ProfileOrangeDark = Color(0xFF5B3F27)
internal val OnProfileOrangeDark = Color(0xFFFFDCC2)
internal val ProfileRoseDark = Color(0xFF5F3445)
internal val OnProfileRoseDark = Color(0xFFFFD9E2)
internal val ProfileGreenDark = Color(0xFF264E37)
internal val OnProfileGreenDark = Color(0xFFCDEDD7)
internal val ProfileOliveDark = Color(0xFF444928)
internal val OnProfileOliveDark = Color(0xFFE0E2C3)
