//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volta.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Volta.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AndroidBiometricPromptNegativeText {
            get {
                return ResourceManager.GetString("AndroidBiometricPromptNegativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity verification.
        /// </summary>
        internal static string AndroidBiometricPromptTitle {
            get {
                return ResourceManager.GetString("AndroidBiometricPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please authenticate to proceed..
        /// </summary>
        internal static string BiometricPromptMessage {
            get {
                return ResourceManager.GetString("BiometricPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string LangPageDone {
            get {
                return ResourceManager.GetString("LangPageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LangPageSearch {
            get {
                return ResourceManager.GetString("LangPageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LangPageTitle {
            get {
                return ResourceManager.GetString("LangPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LockPageLogout {
            get {
                return ResourceManager.GetString("LockPageLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string LockPageUnlock {
            get {
                return ResourceManager.GetString("LockPageUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error. Please try again..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity device is busy..
        /// </summary>
        internal static string WinBiometricBusy {
            get {
                return ResourceManager.GetString("WinBiometricBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity verification is disabled..
        /// </summary>
        internal static string WinBiometricDisabled {
            get {
                return ResourceManager.GetString("WinBiometricDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity verification is not available..
        /// </summary>
        internal static string WinBiometricNotAvailable {
            get {
                return ResourceManager.GetString("WinBiometricNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity device is not found..
        /// </summary>
        internal static string WinBiometricNotPresent {
            get {
                return ResourceManager.GetString("WinBiometricNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity is not registered..
        /// </summary>
        internal static string WinBiometricNotRegistered {
            get {
                return ResourceManager.GetString("WinBiometricNotRegistered", resourceCulture);
            }
        }
    }
}
